name: CI

# When?
on:
  # on these events of a PR
  pull_request:
    # opened: when the PR is opened
    # synchronize: when a new git commit is pushed on the PR's branch
    # reopened: when the PR is re-opened
    types: [opened, synchronize, reopened]
  # on push on the main branch
  push:
    branches: [main]

# What happens?
jobs:
  # JOB: build the docker image
  build:
    # pick a githuhb runner (machine)
    runs-on: ubuntu-latest
    # run these steps
    steps:
      # download the git repo (like git clone)
      - name: Checkout repo
        uses: actions/checkout@v4
      # declare that we need docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # build the docker image
      # NOTE: 
      # this will build the image using the "dockerfile":
      # - that run "npm ci && npm run lint && npm run build"
      # - if somethings fails here the build will fail
      # TODO: add also "npm run test" when you have tests
      - name: Build Docker image
        run: |
          docker build -t next-lifecycle-demo .

  # JOB: deploy to dev (fake)
  deploy-dev:
    # run only if the "build" job succeeded
    needs: build
    # run only on pull requests events
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    # declare which github environment to use
    # Github > Repo > Settings > Environments
    environment: dev
    # run these steps
    steps:
      - name: Fake deploy to DEV
        run: echo "Deploying Docker image to DEV environment"

  # JOB: deploy to staging (fake)
  deploy-staging:
    # run only if the "build" job succeeded
    needs: build
    # run only on new commits on main branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # declare which github environment to use
    # Github > Repo > Settings > Environments
    environment: staging
    # run these steps
    steps:
      - name: Fake deploy to STAGING
        run: echo "Deploying Docker image to STAGING environment"

  # JOB: deploy to production (fake)
  deploy-prod:
    # run only if the "deploy-staging" job succeeded
    needs: deploy-staging
    runs-on: ubuntu-latest
    # declare which github environment to use
    # Github > Repo > Settings > Environments
    environment: production
    # run these steps
    steps:
      - name: Fake deploy to PROD
        run: echo "Deploying Docker image to PRODUCTION"
